export const TIPS: string[] = [
  "Publica el gancho de tu canción en los primeros 3 segundos del vídeo — TikTok decide ahí si sigue reproduciendo.",
  "Sube el mismo sonido con 3 ángulos distintos (baile, storytime, POV) antes de gastar presupuesto en ads: así ves cuál engancha.",
  "Programa el pre-guardado en Spotify/Apple Music al menos 7 días antes del lanzamiento, no el mismo día.",
  "Contesta los primeros 20 comentarios de cada vídeo en la primera hora — el algoritmo premia la conversación temprana.",
  "Escribe el nombre real de la canción en el texto del vídeo, no solo en el audio, para que se pueda buscar luego.",
  "Publica el detrás de cámaras de la grabación antes de anunciar la fecha de lanzamiento: genera curiosidad sin spoilear.",
  "No repitas el mismo gancho más de 2 veces por semana en tu cuenta; cambia el encuadre o el contexto.",
  "Manda el audio a 5-10 creadores medianos antes del lanzamiento — su alcance orgánico suele rendir más que un anuncio pagado.",
  "La portada cuenta una historia en miniatura: pruébala en tamaño de icono de perfil antes de darla por buena.",
  "Sube el videoclip completo a YouTube el mismo día del single — esperar semanas te hace perder impulso de búsqueda.",
  "Revisa los créditos de cada colaborador en la distribuidora antes del lanzamiento: un nombre mal escrito en Spotify tarda semanas en corregirse.",
  "Si hay featuring, coordina que ambos publiquéis el mismo día — el algoritmo premia el pico de actividad cruzada.",
  "Guarda 2-3 ideas de contenido de reserva para la semana de lanzamiento, por si el vídeo principal no despega.",
  "Usa encuestas en las stories antes de lanzar para que la audiencia elija portada o título alternativo: sube el compromiso.",
  "No descartes el pitch a playlists editoriales por llegar tarde — muchas aceptan envíos hasta 48h antes si la metadata está lista.",
  "El mejor momento para publicar en TikTok es cuando tu audiencia está activa, no la hora \"genérica\" de un blog — mira tus propias estadísticas.",
  "Etiqueta el género y el mood en la descripción del vídeo, no solo el nombre de la canción: ayuda al algoritmo a encontrar oyentes afines.",
  "Con presupuesto ajustado, prioriza playlisting sobre ads — suele traer oyentes más fieles por euro invertido.",
  "Deja al menos 3 días entre \"pre-producción cerrada\" y la fecha de lanzamiento: siempre surge un imprevisto de última hora.",
  "Tras el lanzamiento, mira qué vídeo de TikTok trajo más oyentes reales (no solo vistas) y repite ese formato en el siguiente single.",
];
